services:
  client:
    image: "markeybass/multi-client"
    mem_limit: 128m
    hostname: client
  server:
    image: "markeybass/multi-server"
    mem_limit: 128m
    # we call the server api because that what the nginx server will be looking for
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "markeybass/multi-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "markeybass/multi-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"